"""init migration

Revision ID: 139eec9ec10e
Revises: None
Create Date: 2015-02-09 19:55:09.716063

"""

# revision identifiers, used by Alembic.
revision = '139eec9ec10e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
