"""empty message

Revision ID: 1a6fc1c18386
Revises: 35cee0e69876
Create Date: 2015-03-11 14:15:41.209975

"""

# revision identifiers, used by Alembic.
revision = '1a6fc1c18386'
down_revision = '35cee0e69876'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keepaliveds', sa.Column('back_ip', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'keepaliveds', ['back_ip'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keepaliveds')
    op.drop_column('keepaliveds', 'back_ip')
    ### end Alembic commands ###
