"""empty message

Revision ID: 29790b0ea240
Revises: 2b2a6de77fa8
Create Date: 2015-03-06 11:16:10.126361

"""

# revision identifiers, used by Alembic.
revision = '29790b0ea240'
down_revision = '2b2a6de77fa8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
