"""empty message

Revision ID: 2b2a6de77fa8
Revises: 2f21235672ad
Create Date: 2015-03-06 11:13:53.018302

"""

# revision identifiers, used by Alembic.
revision = '2b2a6de77fa8'
down_revision = '2f21235672ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
