"""add idc

Revision ID: 2f21235672ad
Revises: None
Create Date: 2015-02-15 14:40:39.910664

"""

# revision identifiers, used by Alembic.
revision = '2f21235672ad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'hosts', sa.Column('idc_id', sa.Integer(), nullable=True))
    op.add_column(u'vhosts', sa.Column('idc_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'vhosts', 'idc_id')
    op.drop_column(u'hosts', 'idc_id')
    op.drop_table('idcs')
    ### end Alembic commands ###
