"""empty message

Revision ID: 3133bb2dad78
Revises: 58e6e53f0bb2
Create Date: 2015-03-10 18:44:12.945569

"""

# revision identifiers, used by Alembic.
revision = '3133bb2dad78'
down_revision = '58e6e53f0bb2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memcacheds', u'idc_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memcacheds', sa.Column(u'idc_id', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
