"""empty message

Revision ID: 35cee0e69876
Revises: 3133bb2dad78
Create Date: 2015-03-10 18:45:29.965388

"""

# revision identifiers, used by Alembic.
revision = '35cee0e69876'
down_revision = '3133bb2dad78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
