"""empty message

Revision ID: 3e7eb5b9b6b
Revises: 540686d36831
Create Date: 2015-03-09 15:18:18.512206

"""

# revision identifiers, used by Alembic.
revision = '3e7eb5b9b6b'
down_revision = '540686d36831'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memcacheds', u'master')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memcacheds', sa.Column(u'master', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###
