"""add log

Revision ID: 3f72c5bf02e3
Revises: 405a36d3b6d0
Create Date: 2015-03-16 18:45:40.064962

"""

# revision identifiers, used by Alembic.
revision = '3f72c5bf02e3'
down_revision = '405a36d3b6d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('removable', sa.Boolean(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('modify_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_info', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    ### end Alembic commands ###
