"""empty message

Revision ID: 405a36d3b6d0
Revises: None
Create Date: 2015-03-16 18:44:33.255387

"""

# revision identifiers, used by Alembic.
revision = '405a36d3b6d0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
