"""empty message

Revision ID: 465a05278152
Revises: ce52345626
Create Date: 2015-03-14 14:29:14.003898

"""

# revision identifiers, used by Alembic.
revision = '465a05278152'
down_revision = 'ce52345626'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keepaliveds', sa.Column('backup_host_interface', sa.String(length=64), nullable=True))
    op.add_column('keepaliveds', sa.Column('backup_ip', sa.String(length=64), nullable=True))
    op.add_column('keepaliveds', sa.Column('deployed', sa.Boolean(), nullable=True))
    op.add_column('keepaliveds', sa.Column('host_interface', sa.String(length=64), nullable=True))
    op.add_column('keepaliveds', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('keepaliveds', u'back_ip')
    # op.drop_constraint(u'back_ip', 'keepaliveds')
    op.create_unique_constraint(None, 'keepaliveds', ['backup_ip'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keepaliveds')
    op.create_unique_constraint(u'back_ip', 'keepaliveds', [u'back_ip'])
    op.add_column('keepaliveds', sa.Column(u'back_ip', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('keepaliveds', 'status')
    op.drop_column('keepaliveds', 'host_interface')
    op.drop_column('keepaliveds', 'deployed')
    op.drop_column('keepaliveds', 'backup_ip')
    op.drop_column('keepaliveds', 'backup_host_interface')
    ### end Alembic commands ###
