"""empty message

Revision ID: 52a548f9155a
Revises: 4b52410efda
Create Date: 2015-03-31 17:29:37.747749

"""

# revision identifiers, used by Alembic.
revision = '52a548f9155a'
down_revision = '4b52410efda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('status_json', sa.String(length=4096), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'status_json')
    ### end Alembic commands ###
