"""init migration

Revision ID: 540686d36831
Revises: None
Create Date: 2015-03-06 17:33:03.505788

"""

# revision identifiers, used by Alembic.
revision = '540686d36831'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
