"""empty message

Revision ID: 564db81ef9ee
Revises: 1d345ad41712
Create Date: 2015-03-10 11:24:06.344612

"""

# revision identifiers, used by Alembic.
revision = '564db81ef9ee'
down_revision = '1d345ad41712'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keepaliveds',
    sa.Column('removable', sa.Boolean(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.Column('modify_time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.add_column(u'idcs', sa.Column('mem_size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'idcs', 'mem_size')
    op.drop_table('keepaliveds')
    ### end Alembic commands ###
