"""empty message

Revision ID: 58e6e53f0bb2
Revises: 564db81ef9ee
Create Date: 2015-03-10 11:41:38.485416

"""

# revision identifiers, used by Alembic.
revision = '58e6e53f0bb2'
down_revision = '564db81ef9ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('mem_size', sa.Integer(), nullable=True))
    op.drop_column('idcs', u'mem_size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idcs', sa.Column(u'mem_size', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('hosts', 'mem_size')
    ### end Alembic commands ###
